
name: Trantojson

on: 
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.11"] 

    steps:
      - uses: actions/checkout@v3

      - name: trantojson
        run: |
          git clone https://github.com/richardwilkes/gcs_master_library.git
          find ./gcs_master_library/Library|egrep  ".(skl|adq|adm|eqm|eqp|attr)$" >> list.txt
          while read line
          do
          echo $line
          python3 ./.github/workflows/trans_to_json.py "$line"
          done <list.txt
                    
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: "gcs_master_library_en_json"


        
