
name: TrantoChineseLibrary
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.11"] 

    steps:
      - uses: actions/checkout@v3


      - name: trantojson
        run: |
          git clone https://github.com/richardwilkes/gcs_master_library.git
          find . |grep  "Skills_zh_Hans.json" >> skl.list
          while read line
          do
          echo $line
          python3 ./.github/workflows/trans_to_chinese.py "$line"
          done <skl.list
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: "gcs_library_chinese"


