
name: TrantoChineseLibrary
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.11"] 

    steps:
      - uses: actions/checkout@v3


      - name: trantojson
        run: |
          git clone https://github.com/richardwilkes/gcs_master_library.git
          find ./gcs_master_library/|egrep  ".skl|.adq" >> list.txt
          while read line
          do
          echo $line
          python3 ./.github/workflows/trans_to_chinese.py "$line"
          done <list.txt
          rm -rf ./Library
          mv -f ./gcs_chinese_library/Library .
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "Library"


